### Site info:
title: /dav/null
tagline: Posts about code etc. 
author: dvalts 
email: dvalts@gmail.coom
description: "dvalts' ramblings about code and life" # You can edit this line in _config.yml. It will appear in your document head meta and in your feed.xml site description
keywords: "c++, python"
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://decvalts.github.io" # the base hostname & protocol for your site
locale: en_US

### Personal info and site tools info:
twitter_username: dvalts
github_username:  decvalts
favicon:     "/images/favicon.ico"
aboutme: THello, World! # these are shown on aboutme-sidebar.
aboutme_photo:  # your photo.


### Site setting:
ShowContactInfo: "True" # Personal Info (twitter,github,email) can be seen on aboutme-sidebar, those info only shown when ShowContactInfo == True
default_column: "two" # blog style: two columns, if default_column != "two", you will see a one column blog.
default_locale: "en" # blog sidebar language set, only include: English(en) and Chinese (cn)

locales:
    en:
      Aboutme: "About"
      Archives: "Archives"
      Blogroll: "Blogroll"
      Categories: "Categories"
      Copyright_Notice: "Copyright Notice"
      Recent_Posts: "Recent Posts"
      Tags: "Tags"
      Previous: "Older"
      Next: "Newer"
      PostedInCategories: "Posted in"
      Taggedwith: "and tagged"  
      PostDate: "on "

### your Blogroll info, only name can shown on the page.

Blogroll:
    - name: LSDTopoTools
      href: http://LSDtopotools.github.io
      title: LSDTopoTools homepage

      

### Build settings
markdown: kramdown
highlighter: pygments
paginate: 5
