### Site info:
title: /dav/null
tagline: Software Engineer
author: dvalts
email: dvalts@gmail.com
description: "dvalts' ramblings about software and programming" # You can edit this line in _config.yml. It will appear in your document head meta and in your feed.xml site description
keywords: "c++, python"
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://dvalters.github.io" # the base hostname & protocol for your site
locale: en_US

### Personal info and site tools info:
twitter_username: dvalts
github_username:  dvalters
favicon:
aboutme: I like writing code for scientific research. Occasionally tinkering with other non-sciencey projects too.  # these are shown on aboutme-sidebar.
aboutme_photo:  "/images/profile.jpeg"


### Site setting:
ShowContactInfo: "True" # Personal Info (twitter,github,email) can be seen on aboutme-sidebar, those info only shown when ShowContactInfo == True
default_column: "two" # blog style: two columns, if default_column != "two", you will see a one column blog.
default_locale: "en" # blog sidebar language set, only include: English(en) and Chinese (cn)

locales:
    en:
      Aboutme: "About"
      Archives: "Archives"
      Blogroll: "Blogroll"
      Categories: "Categories"
      Copyright_Notice: "Copyright Notice"
      Recent_Posts: "Recent Posts"
      Tags: "Tags"
      Previous: "Older"
      Next: "Newer"
      PostedInCategories: "Posted in"
      Taggedwith: "and tagged"
      PostDate: "on "

### your Blogroll info, only name can shown on the page.

Blogroll:
    - name: LSDCodingBlog
      href: https://lsdtopotools.github.io/LSDCodingBlog/
      title: Blog I contribute to about the coding process for LSDTopoTools

    - name: LSDTopoTools
      href: http://LSDtopotools.github.io
      title: LSDTopoTools homepage

    - name: PyCAS
      href: https://atmoscoders.github.io/PyCAS/home
      title: A python users group in the Centre for Atmospheric Science



### Build settings
markdown: kramdown
highlighter: rouge
paginate: 5
